name: Deploy React Application
on:
  push:
    branches:
      - 'main'
jobs:
  test_react_app:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test the application
        run: npm run test
  lint_react_app:
    runs-on: ubuntu-latest
    needs: test_react_app
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint the application
        run: npm run lint
  build_react_app:
    runs-on: ubuntu-latest
    needs: lint_react_app
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build the application
        run: npm run build
      - name: Deploy the application
        run: echo Deploying...

